# 欢迎来到 Jekyll！
#
# 这个设置文件是用配置整个站点，或者那些你希望设置一次就几乎不需要再改动的东西。
# 如果你发现你需要经常改动这个文件，考虑使用 Jekyll 的数据文件功能吧。
#
# 因为一些技术原因，当使用 'bundle exec jekyll serve' 运行的时候，对这个文件做出的改动
# *不会* 立即反映。如果改动了这个文件，请重启服务器程序。
#
# 如果你不熟悉 YMAL 语法，这里有一些快速参考：
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# 网站设置
# 这些用于定制您的新网站。如果你查看 HTML 文件，你会看到它们使用 {{ site.title }},
# {{ site.email }} 等访问这个问价。在这里，你可以用你喜欢的方式生成或者自定义任何变量，它们
# 可以在模板中使用 {{ site.myvariable }} 来使用。

title: 我的博客
email: zoloak@163.com
description: >- # this means to ignore newlines until "baseurl:"
  我的博客，我创建了这个博客，不过我就是这个博客。我在循环定义中诞生，是我
  创建了我自己。所以我说我的巨牛逼博客的时候，我其实是在说我巨牛逼。
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
# twitter_username: nope
github_username:  zoloak

# Build settings
theme: minima
plugins:
  - jekyll-feed

defaults:
  - scope:
      path: ""
      type: reviews
    values:
      layout: review

# 集合
collections:
  reviews:
    output: false
    permalink: /:collection/:path/

# 永久连结
permalink: /:categories/:year-:month-:day-:title:output_ext

# 在生成的时候排除的文件
exclude:
  - zoloak.github.io.code-workspace

# markdown render engine.
markdown:         kramdown
kramdown:
  auto_ids:               true
  input:                  GFM # GitHub Flavored Markdown Spec
  math_engine:            mathjax
  smart_quotes:           lsquo,rsquo,ldquo,rdquo
  toc_levels:             1..6
  syntax_highlighter:     rouge
  syntax_highlighter_opts:
    guess_lang:           true

# how to use
# - in laypots:
# <link rel="stylesheet" href="{{site.baseurl}}/gitbook/rouge/{{ site.syntax_highlighter_style }}.css">
#
# used rouge to highlight
# use `rougify help style` to find a theme
# use `rougify style gruvbox > .\assets\css\rouge\gruvbox.css` to genrate a theme
syntax_highlighter_style: gruvbox

markdown_ext:     markdown,mkdown,mkdn,mkd,md
